apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
namespace: cert-manager

# Cert Manager Chart
helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: "v1.9.1"
  releaseName: cert-manager-release
  releaseNamespace: cert-manager
  values: values.yaml